"""add margin_rate to mortgages

Revision ID: 68c381537c96
Revises: 032
Create Date: 2026-03-25 18:30:13.946876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68c381537c96'
down_revision: Union[str, None] = '032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortgages', sa.Column('margin_rate', sa.Numeric(precision=5, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortgages', 'margin_rate')
    # ### end Alembic commands ###
