"""Centralized per-user resource limits."""

MAX_POSITIONS_PER_USER = 500
MAX_TRANSACTIONS_PER_USER = 10000
MAX_PRECIOUS_METAL_ITEMS_PER_USER = 200
MAX_PROPERTIES_PER_USER = 20
MAX_MORTGAGES_PER_PROPERTY = 10
MAX_EXPENSES_PER_PROPERTY = 500
MAX_INCOME_PER_PROPERTY = 500
MAX_WATCHLIST_PER_USER = 200
MAX_WATCHLIST_TAGS_PER_USER = 50
MAX_IMPORT_PROFILES_PER_USER = 20
MAX_PE_HOLDINGS_PER_USER = 20
MAX_PE_VALUATIONS_PER_HOLDING = 50
MAX_PE_DIVIDENDS_PER_HOLDING = 50
